/**
 * @jest-environment jsdom
 */
import {
  NOTEBOOK_LLM_CONFIG_EXPANDED_UI_STORAGE_KEY,
  NOTEBOOK_LLM_CONFIGS_STORAGE_KEY,
  NOTEBOOK_LLM_DEFAULT_CONFIG_STORAGE_KEY,
  NOTEBOOK_LLM_DOMAIN_USAGE_STATS_STORAGE_KEY,
  NOTEBOOK_LLM_EXPERT_MODE_CONFIGS_STORAGE_KEY,
  NOTEBOOK_LLM_KNOWLEDGE_HISTORY_STORAGE_KEY,
} from '../notebookLLMStorageKeys';
import {
  NOTEBOOK_LLM_CONFIG_EXPANDED_UI_STORAGE_KEY as K_EXPAND,
  NOTEBOOK_LLM_CONFIGS_STORAGE_KEY as K_CFG,
  NOTEBOOK_LLM_DEFAULT_CONFIG_STORAGE_KEY as K_DEF,
  NOTEBOOK_LLM_DOMAIN_USAGE_STATS_STORAGE_KEY as K_DOM,
  NOTEBOOK_LLM_EXPERT_MODE_CONFIGS_STORAGE_KEY as K_EXP,
  NOTEBOOK_LLM_KNOWLEDGE_HISTORY_STORAGE_KEY as K_HIST,
} from '../notebookLLMService';

describe('notebookLLMStorageKeys', () => {
  it('localStorage 키 문자열 계약', () => {
    expect(NOTEBOOK_LLM_DOMAIN_USAGE_STATS_STORAGE_KEY).toBe('domainUsageStats');
    expect(NOTEBOOK_LLM_KNOWLEDGE_HISTORY_STORAGE_KEY).toBe('knowledgeHistory');
    expect(NOTEBOOK_LLM_EXPERT_MODE_CONFIGS_STORAGE_KEY).toBe('expertModeConfigs');
    expect(NOTEBOOK_LLM_CONFIGS_STORAGE_KEY).toBe('notebookLLMConfigs');
    expect(NOTEBOOK_LLM_DEFAULT_CONFIG_STORAGE_KEY).toBe('defaultNotebookLLMConfig');
    expect(NOTEBOOK_LLM_CONFIG_EXPANDED_UI_STORAGE_KEY).toBe('notebook-llm-config-expanded');
  });

  it('notebookLLMService 재보내기와 동일', () => {
    expect(K_DOM).toBe(NOTEBOOK_LLM_DOMAIN_USAGE_STATS_STORAGE_KEY);
    expect(K_HIST).toBe(NOTEBOOK_LLM_KNOWLEDGE_HISTORY_STORAGE_KEY);
    expect(K_EXP).toBe(NOTEBOOK_LLM_EXPERT_MODE_CONFIGS_STORAGE_KEY);
    expect(K_CFG).toBe(NOTEBOOK_LLM_CONFIGS_STORAGE_KEY);
    expect(K_DEF).toBe(NOTEBOOK_LLM_DEFAULT_CONFIG_STORAGE_KEY);
    expect(K_EXPAND).toBe(NOTEBOOK_LLM_CONFIG_EXPANDED_UI_STORAGE_KEY);
  });
});
